name: Update MSTR-BTC notebook
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  update_nb:
    name: Update MSTR-BTC notebook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          cache: 'pip'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Script and Update Notebook
        run: |
          chmod +x "${GITHUB_WORKSPACE}/run.sh"
          "${GITHUB_WORKSPACE}/run.sh"
      - name: Commit and Push Changes
        run: |
          git config --local user.email "fuuuumin314@gmail.com"
          git config --local user.name "fuuuumin"
          git add docs/index.html
          git commit -m "Updated plot on `date` with GitHub Actions"
          git push origin main